### ISSUE TITLE
Importation de données problématique

### ISSUE THREAD

**Issue by ShawnLemaire** [BioDataScience-Course/B02Ga_urchin#1]
Bonjour, 

Je suis sur le projet Urchin et j'ai voulu sur le notebook importer mes données. Cela a fonctionné puisque j'arrive à utiliser le jeu de données pour faire des graphiques ou autres analyses mais quand j'essaie de Knit, voilà le message d'erreur qu'il me met.
![image](https://user-images.githubusercontent.com/72133994/140605117-cf59d698-8636-48ca-86cc-dc9b891d01e9.png)
Que dois faire ?

Merci.

**Comment by phgrosjean** [comment]
Hé, hé, il y avait un piège et tu es tombé dedans. Le message te dit que la première entrée de l'entête YAML (plus précisément en sa ligne 1 et colonne 24), il y a une erreur. La ligne 1 de l'entête est le titre. Regardes bien (surtout les ponctuations)!

**Comment by ShawnLemaire** [comment]
Merci beaucoup Monsieur.
On a résolu le problème.
